name = "stm32l0xx_cmsis"
description = "CMSIS library for STMicroelectronics' STM32L0 MCU series"
long-description = """
Common Microcontroller Software Interface Standard (CMSIS) library for the
STMicroelectronics STM32L0 series of microcontrollers, ported from C to Ada.
"""
version = "0.7.2-dev"
tags = ["arm", "embedded", "cmsis", "stm32", "cortex-m0"]
notes = "Development version"

authors            = ["Emanuele Zarfati"]
maintainers        = ["Emanuele Zarfati <zarfati.tecno@gmail.com>"]
maintainers-logins = ["itafraze"]
licenses           = "Apache-2.0"

[[depends-on]]
gnat_arm_elf = "^13.2.1"

[build-switches]
"*".ada_version = "Ada2022"

[build-switches.release]
optimization   = "size" # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info     = "no"   #
runtime_checks = "none" # "-gnatp"
compile_checks = "none" #
contracts      = "no"   #
style_checks   = "yes"  # "-gnaty3", "-gnatya", "-gnatyA", "-gnatyB", "-gnatyb", "-gnatyc", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatym", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyt", "-gnatyu", "-gnatyx"

[build-switches.validation]
optimization   = "size"       # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info     = "no"         #
runtime_checks = "everything" # "-gnato"
compile_checks = "errors"     # "-gnatwa", "-gnatw.X", "-gnatVa", "-gnatwe"
contracts      = "yes"        # "-gnata"
style_checks   = "yes"        # "-gnaty3", "-gnatya", "-gnatyA", "-gnatyB", "-gnatyb", "-gnatyc", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatym", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyt", "-gnatyu", "-gnatyx"

[build-switches.development]
optimization   = "debug"    # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info     = "yes"      # "-g"
runtime_checks = "default"  #
compile_checks = "warnings" # "-gnatwa", "-gnatw.X", "-gnatVa"
contracts      = "yes"      # "-gnata"
style_checks   = "no"       #

[configuration]
generate_ada = false
generate_gpr = true
generate_c   = false

[configuration.variables]
Device               = { type = "Enum", values = ["stm32l011d4"], default = "stm32l011d4" }
With_Startup         = { type = "Boolean", default = true }
Runtime              = { type = "Enum", values = ["light"], default = "light" }
Disable_Restrictions = { type = "Boolean", default = false }
