= Alire Crate - Stm32l0xx Cmsis
:toc:

This repository provides the
link:https://www.arm.com/technologies/cmsis[Common Microcontroller Software
Interface Standard] (CMSIS) library for the STMicroelectronics
link:https://www.st.com/en/microcontrollers-microprocessors/stm32l0-series.html[STM32L0]
MCU series and is intended to be distributed via the
link:https://alire.ada.dev/[Alire] package manager. This library, ported from
C to Ada, is based on the following projects:

.Credits
[cols="3,^1",width=75%,frame=none,grid=rows,role=center]
|===
| | Version

| Arm Software's CMSIS Version 5 |
link:https://github.com/ARM-software/CMSIS_5/tree/5.9.0[5.9.0]

| STMicroelectronics's STM32CubeL0 CMSIS Device MCU Component |
link:https://github.com/STMicroelectronics/cmsis_device_l0/tree/v1.9.3[v1.9.3]

|===

== License

Licensed under the link:http://www.apache.org/licenses/LICENSE-2.0[Apache
License, Version 2.0].

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

== Development

Requests and reporting::
Please report bugs or feature requests to the project maintainers, preferably
using the
link:https://gitlab.com/ezetec-alire-crates/stm32l0xx-cmsis/-/issues[issues
tracker].

Workflow:: The project development workflow is inspired by the
link:https://nvie.com/posts/a-successful-git-branching-model/[GitFlow]
branching model. Although strict naming conventions are not enforced,
`feature` branches should branch from `develop` and `fix` branches from `main`
or latest `release`.