= Alire Crate - Stm32l0xx Cmsis
:toc:

This repository provides the link:https://www.arm.com/technologies/cmsis[Common
Microcontroller Software Interface Standard] (CMSIS) library for
STMicroelectronics's MCU series
link:https://www.st.com/en/microcontrollers-microprocessors/stm32l0-series.html[STM32L0]
and intended to be distribute through the link:https://alire.ada.dev/[Alire]
package manager. This library, ported from C to Ada, is based on:

.Sources
[cols="3,^1",width=75%,frame=none,grid=rows,role=center]
|===
|Project|Version

| Arm Software's CMSIS Version 5 |
link:https://github.com/ARM-software/CMSIS_5/tree/5.9.0[5.9.0]

| STMicroelectronics's STM32CubeL0 CMSIS Device MCU Component |
link:https://github.com/STMicroelectronics/cmsis_device_l0/tree/v1.9.3[v1.9.3]

|===

== Repository structure

.Content
[cols="1,3",width=75%,frame=none,grid=rows,role=center]
|===
|Path|Description

|link:./src/[`src/`] | Library source files

|link:./tests/[`tests/`] | Library test files

|===

== License

Licensed under the link:http://www.apache.org/licenses/LICENSE-2.0[Apache
License, Version 2.0].

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

== Development

System View Description (SVD) files::
The link:https://github.com/AdaCore/svd2ada[svd2ada] utility is used to
generate the source files with descriptions of the memory-mapped registers of
peripherals. This utility can be retrieved through Alire with `alr get
svd2ada` and built with `alr with gnat-native` once the `gnat-native`
toolchain is added as dependency. As an example, the device files for
STM32L0x1 MCUs are generated with command:
+
[source,bash]
----
svd2ada --gen-interrupts --gen-uint-always --no-uint-subtypes \
   --base-types-package HAL --package Cmsis.Device --output src/stm32l0x1/ \
   src/stm32l0x1/stm32l0x1.svd
----
+
The official SVD files can be obtained directly from STMicroelectronics,
located within the CAD resources section of each device webpage (for example
link:https://www.st.com/en/microcontrollers-microprocessors/stm32l011d4.html#cad-resources[stm32l011d4's
webpage]). At the time of writing, the SVD files supplied by
STMicroelectronics are affected by errors, as demonstrated by the effort spent
by the Rust community on project
link:https://github.com/stm32-rs/stm32-rs[stm32-rs] to patch and keep them up
to date. Unfavourably, these patched SVD cannot be supplied to `svd2ada` as
the tool does not yet support the latest SVD specification. As a consequence,
the device files here committed contain errors. Double check them before use.

Startup file and linker script::
The link:https://github.com/AdaCore/startup-gen[startup-gen] utility is used
to generate the startup file `crt0.S` and the linker script `link.ld` based on
the template files `crt0.S.tmplt` and `link.ld.tmplt` respectively. Similarly
to link:https://github.com/AdaCore/svd2ada[svd2ada], this utility can be
retrieved with `alr get startup-gen` and built with `alr with gnat-native`
once the `gnat-native` toolchain is added as dependency. The files cen be
generated with, for example, executing:
+
[source,bash]
----
startup_gen -P stm32l0xx_cmsis.gpr \
   -l share/stm32l0xx_cmsis/link.ld -s src/stm32l0x1/startup/crt0.S
----

Tests on emulated target::
The target platform can be emulated using GNATemu, which cannot be found
available through Alire at the time of writing. However non-GNATPro users may
still find available ARM ELF GNAT Community Edition, which ships also the
`arm-eabi-gnatemu` binary, at AdaCore's
link:https://www.adacore.com/download[Download page].
+
Sub-crate project link:./tests/tests.gpr[`tests/tests.gpr`] supplies the
`Emulator` package with minimal working configuration. Assuming
`arm-eabi-gnatemu` exists in `PATH`, create for convenience the Alire alias
`gnatemu` with
+
[source,bash]
----
alr config --global --set alias.gnatemu "exec -P1 arm-eabi-gnatemu -P"
----
+
and start the emulator within the `tests` subfolder with `alr gnatemu`. In
another terminal window launch GDB with
+
[source,bash]
----
arm-eabi-gdb -x share/tests/gdbinit
----
